= Configuration

{{ start }}++++
{% method %}
== Logging In
Once apiman is running, you should be able to log in to the API Manager by pointing your browser at the following URL:

....
http://localhost:8080/apimanui/
....

You may log in with credentials *admin/admin123!*

{% common %}
[CAUTION]
====
We strongly advise that you immediately change the Keycloak admin user's password, as well as the *_admin_* user found in the *_apiman_* realm!

You can do that by navigating to http://localhost:8080/auth/admin/.
====
{% endmethod %}
{{ end }}++++


== General Configuration

Of course apiman is made up of a number of different components, many of which can be configured to use various implementations and/or providers.
When downloading and installing apiman, the default distribution includes reasonable default values for all options.
This section details these options and explains the default values.

=== Configuration Properties

All of the apiman WARs share a common configuration file called *apiman.properties*, which can be found in *standalone/configuration*.
This file therefore contains configuration settings for all three applications (API Manager, API Manager UI, API Gateway).

Please refer to the `apiman.properties` file itself, as well as this document, for more information on each property's purpose and possible values.

TIP: If you are running a non-Servlet gateway implementation (e.g. Vert.x), then you should refer to that gateway's configuration documentation to understand how to configure it.

{{ start }}++++
{% method %}
=== API Manager Database

The API Manager, by default, is a typical CDI application and uses JPA/Hibernate to persist its data.
The JPA layer requires a data source to connect to a supported database.
When running in WildFly this datasource is made available by deploying the following file:

....
standalone/deployments/apiman-ds.xml
....

Out of the box this data source is usually a simple H2 configuration, but you can (of course) change
it to support whatever database you desire.

{% common %}
```xml
<?xml version="1.0" encoding="UTF-8"?>
<datasources>
  <datasource jndi-name="jdbc/ApiManDT" pool-name="apiman-manager-api" enabled="true"
    use-java-context="true">
    <connection-url>jdbc:h2:${jboss.server.data.dir}${/}h2${/}apiman-manager-api;MVCC=true</connection-url>
    <driver>h2</driver>
    <security>
      <user-name>sa</user-name>
    </security>
  </datasource>
</datasources>
```
{% endmethod %}
{{ end }}++++

The project comes with DDLs for MySQL and PostgreSQL, to hopefully make it easy to switch away from H2.
Note that switching databases also requires a change to the apiman.properties file.
The following should be changed to appropriate values for your database:

```properties
apiman.hibernate.dialect=io.apiman.manager.api.jpa.ApimanMySQL5Dialect
apiman.hibernate.hbm2ddl.auto=validate
```

Note that the following dialects are available:

* io.apiman.manager.api.jpa.ApimanH2Dialect
* io.apiman.manager.api.jpa.ApimanMySQL5Dialect
* io.apiman.manager.api.jpa.ApimanOracle12Dialect
* io.apiman.manager.api.jpa.ApimanPostgreSQLDialect

You can, of course, set the hbm2ddl property to "update" so that hibernate automatically creates the database structure when it starts up.
Additional DDLs for various databases can be found in *apiman/ddls/*.

== Gateway API Authentication

The Gateway's REST API is what the API Manager invokes when publishing APIs and Client Apps
to the Gateway.  This REST API should be protected, often using BASIC authentication.  By default,
the Gateway REST API requires BASIC authentication credentials, as well as a role of *apipublisher*.
In other words, the Gateway REST API can only be invoked by a valid user, and that user must have
the *apipublisher* role.
