= Configuration Guide
:toc:

Of course apiman is made up of a number of different components, many of which can be configured to use various implementations and/or providers.
When downloading and installing apiman, the default distributions include reasonable default values for all options.
This section details these options and explains the default values.

Apiman runs on multiple platforms, each with slightly different ways of specifying configuration; however they are abstractions of identical concepts. Not all platforms can run all components.

You should refer to the platform's specific sections for further details.

== API Manager Database

++++
<details>
<summary>Platform Support</summary>
++++
[format="csv", options="header,autowidth", cols="^,^"]
|===
Servlet,Vert.x
✅,-
|===
++++
</details>
++++

The API Manager, by default, is a typical CDI application and uses JPA/Hibernate to persist its data.
The JPA layer requires a data source to connect to a supported database.
When running in WildFly this datasource is made available by deploying the following file:

....
standalone/deployments/apiman-ds.xml
....

Out of the box this data source is usually a simple H2 configuration, but you can (of course) change it to support whatever database you desire.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<datasources>
  <datasource jndi-name="jdbc/ApiManDT" pool-name="apiman-manager-api" enabled="true"
    use-java-context="true">
    <connection-url>jdbc:h2:${jboss.server.data.dir}${/}h2${/}apiman-manager-api;MVCC=true</connection-url>
    <driver>h2</driver>
    <security>
      <user-name>sa</user-name>
    </security>
  </datasource>
</datasources>
```

The project comes with DDLs for MySQL and PostgreSQL, to hopefully make it easy to switch away from H2.
Note that switching databases also requires a change to the apiman.properties file.
The following should be changed to appropriate values for your database:

```
apiman.hibernate.dialect=io.apiman.manager.api.jpa.ApimanMySQL5Dialect
apiman.hibernate.hbm2ddl.auto=validate
```

Note that the following dialects are available:

* io.apiman.manager.api.jpa.ApimanH2Dialect
* io.apiman.manager.api.jpa.ApimanMySQL5Dialect
* io.apiman.manager.api.jpa.ApimanOracle12Dialect
* io.apiman.manager.api.jpa.ApimanPostgreSQLDialect

You can, of course, set the hbm2ddl property to "update" so that hibernate automatically creates the database structure when it starts up.
Additional DDLs for various databases can be found in *apiman/ddls/*.

== API Gateway Registry

The API Gateway includes a registry that stores the published API and Client App information.
This registry is updated whenever a user publishes an API (or registers a Client App) from
within the API Manager UI.  The registry contains just the configuration information necessary for
the API Gateway to properly apply the appropriate policies to all inbound requests.

Out of the box, the API Gateway is configured to use Elasticsearch to store the published/registered data.

The configuration of the Registry can be found in the *apiman.properties* file.

See section FIXME for more information on modifying Elasticsearch settings.
